# This is a basic workflow that is manually triggered

name: NISTtheDocs2Death
description: Deploys Sphinx-built documentation to https://pages.nist.gov
author: Jonathan Guyer

inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  pages-branch:
    description: 
      The branch linked to your documentation server.
    default: 'nist-pages'
  pages-url:
    description:
      URL of web server for served documentation.
    default: 'https://pages.nist.gov'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Commit documentation changes
      uses: usnistgov/NISTtheDocs2Death@workhorse
      with:
        action: borg_the_docs
        docs-folder: ${{ inputs.docs-folder }}
    - uses: usnistgov/sphinx-action@master
      name: Build HTML
      with:
        docs-folder: ${{ inputs.docs-folder }}
#       - uses: usnistgov/sphinx-action@master
#         name: Build ePUB
#         with:
#           docs-folder: ${{ inputs.docs-folder }}
#           build-command: make epub
#       - uses: usnistgov/sphinx-action@latexpdf
#         name: Build PDF
#         with:
#           docs-folder: ${{ inputs.docs-folder }}
    - name: Commit documentation changes
      uses: usnistgov/NISTtheDocs2Death@workhorse
      with:
        action: update_pages
        docs-folder: ${{ inputs.docs-folder }}
        default-branch: ${{ github.event.repository.default_branch }}
        pages-branch: ${{ inputs.pages-branch }}
        pages-url: ${{ inputs.pages-url }}
    - name: Change ownership
      shell: bash
      run: |
        sudo chown -R runner:docker __nist-pages
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ inputs.pages-branch }}
        directory: __nist-pages
        github_token: ${{ github.token }}
    - name: Set env
      run: |
        artifact=${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}
        echo "ARTIFACT_NAME=${artifact////_}" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3
      name: Upload Documentation Artifacts
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
          docs/_build/html
#             docs/_build/epub/*.epub
#             docs/_build/latex/${{ github.event.repository.name }}.pdf
      # Use always() to always run this step to publish documentation
      # artifacts even when there are failures
      if: ${{ always() }}
