# This is a basic workflow that is manually triggered

name: NISTtheDocs2Death
description: Deploys Sphinx-built documentation to https://pages.nist.gov
author: Jonathan Guyer

inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  pages-branch:
    description: 
      The branch linked to your documentation server.
    default: 'nist-pages'
  pages-url:
    description:
      URL of web server for served documentation.
    default: 'https://pages.nist.gov'
  build-command:
    description:
      The command used to build your documentation.
    required: false
    default: make html
  pre-build-command:
    description:
      Run before the build command, you can use this to install system level
      dependencies, for example with
      "apt-get update -y && apt-get install -y perl"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set env
      shell: bash
      # In a PR, github.ref_name can be, e.g., `12/merge`,
      # which causes downstream grief.
      run: |
        refname=${{ github.ref_name }}
        echo "SANITIZED_REF_NAME=${refname////_}" >> $GITHUB_ENV
    - name: Add cruft to theme
      uses: usnistgov/NISTtheDocs2Death@workhorse
      with:
        action: borg_the_docs
        docs-folder: ${{ inputs.docs-folder }}
    - uses: usnistgov/sphinx-action@master
      name: Build HTML
      with:
        docs-folder: ${{ inputs.docs-folder }}
        build-command: ${{ inputs.build-command }}
        pre-build-command:  ${{ inputs.pre-build-command }}
#       - uses: usnistgov/sphinx-action@master
#         name: Build ePUB
#         with:
#           docs-folder: ${{ inputs.docs-folder }}
#           build-command: make epub
#       - uses: usnistgov/sphinx-action@latexpdf
#         name: Build PDF
#         with:
#           docs-folder: ${{ inputs.docs-folder }}
    - name: Commit documentation changes
      uses: usnistgov/NISTtheDocs2Death@workhorse
      with:
        action: update_pages
        docs-folder: ${{ inputs.docs-folder }}
        default-branch: ${{ github.event.repository.default_branch }}
        pages-branch: ${{ inputs.pages-branch }}
        pages-url: ${{ inputs.pages-url }}
    - name: Change ownership
      shell: bash
      run: |
        sudo chown -R runner:docker __nist-pages
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ inputs.pages-branch }}
        directory: __nist-pages
        github_token: ${{ github.token }}
    - uses: actions/upload-artifact@v3
      name: Upload Documentation Artifacts
      with:
        name: ${{ github.event.repository.name }}-${{ env.SANITIZED_REF_NAME }}-${{ github.sha }}
        path: |
          ${{ inputs.docs-folder }}/_build/html
#             ${{ inputs.docs-folder }}/_build/epub/*.epub
#             ${{ inputs.docs-folder }}/_build/latex/${{ github.event.repository.name }}.pdf
      # Use always() to always run this step to publish documentation
      # artifacts even when there are failures
      if: ${{ always() }}
