# This is a basic workflow that is manually triggered

name: NISTtheDocs2Death
description: Deploys Sphinx-built documentation to https://pages.nist.gov
author: Jonathan Guyer

inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  pages-branch:
    description: 
      The branch linked to your documentation server.
    default: 'nist-pages'

runs:
  using: "composite"
  steps:
    - name: Commit documentation changes
      shell: bash
      run: |
        git clone ${{ github.server_url }}/${{ github.repository }}.git \
          --branch ${{ inputs.pages-branch }} \
          --single-branch nist-pages
        cd nist-pages

        html="html"

        # store built documents in directory named for current branch
        # remove any previous directory of that name
        git rm -r --ignore-unmatch "${html}/${{ github.ref_name }}"
        mkdir -p ${html}
        cp -r "../${{ inputs.docs-folder }}_build/html" "${html}/${{ github.ref_name }}"

        # store built documents in latest/
        # (but only do this for default branch of repo)
        if ${{ github.ref_name == github.event.repository.default_branch }}
        then
          # remove any previous directory of that name
          git rm -r --ignore-unmatch "${html}/latest"
          mkdir -p ${html}
          cp -r "../${{ inputs.docs-folder }}_build/html" "${html}/latest"
        fi

        # jekyll conflicts with sphinx' underlined directories and files
        touch .nojekyll

        # build index.html with available documentation versions
        rm -f includes/versions.html
        mkdir -p includes
        echo "<ul>" >> includes/versions.html
        for path in ${html}/*
        do
            version="${path##*/}"
            echo "<li><a href=\"/${{ github.event.repository.name }}/${path}/index.html\">${version}</a>" >> includes/versions.html
        done
        echo "</ul>" >> includes/versions.html

        # build index.html with available documentation versions
        rm -f index.html
        cat _templates/index_header.html >> index.html
        echo "<div class=\"documentation-versions\">" >> index.html
        cat includes/versions.html >> index.html
        echo "</div>" >> index.html
        cat _templates/index_footer.html >> index.html

        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation for ${{ github.ref_name }}@${{ github.sha }}" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ inputs.pages-branch }}
        directory: nist-pages
        github_token: ${{ github.token }}
