# This is a basic workflow that is manually triggered

name: NISTtheDocs2Death
description: Deploys Sphinx-built documentation to https://pages.nist.gov
author: Jonathan Guyer

inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  separated-layout:
    description:
      Whether sphinx docs have separate source and build directories.
    required: true
    default: false
  pages-branch:
    description: 
      The branch linked to your documentation server.
    default: 'nist-pages'
  pages-url:
    description:
      URL of web server for served documentation.
    default: 'https://pages.nist.gov'
  build-command:
    description:
      The command used to build your documentation.
    required: false
    default: make html
  pre-build-command:
    description:
      Run before the build command, you can use this to install system level
      dependencies, for example with
      "apt-get update -y && apt-get install -y perl"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        set-safe-directory: /github/workspace
#     - name: Work around https://github.com/actions/checkout/issues/766
#       shell: bash
#       run: |
#         git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Set env
      shell: bash
      # In a PR, github.ref_name can be, e.g., `12/merge`,
      # which causes downstream grief.
      run: |
        refname=${{ github.ref_name }}
        echo "SANITIZED_REF_NAME=${refname////_}" >> $GITHUB_ENV
        if ${{ inputs.separated-layout }}
        then
            echo "BUILD_DIR=build" >> $GITHUB_ENV
        else
            echo "BUILD_DIR=_build" >> $GITHUB_ENV
        fi
    - name: Add cruft to theme
      id: borg-the-docs
      uses: usnistgov/NISTtheDocs2Death@borg_the_docs
      with:
        docs-folder: ${{ inputs.docs-folder }}
        separated-layout: ${{ inputs.separated-layout }}
    - uses: usnistgov/sphinx-action@master
      name: Build HTML
      with:
        docs-folder: ${{ steps.borg-the-docs.outputs.borged-docs-folder }}
        build-command: ${{ inputs.build-command }}
        pre-build-command:  ${{ inputs.pre-build-command }}
#       - uses: usnistgov/sphinx-action@master
#         name: Build ePUB
#         with:
#           docs-folder: ${{ steps.borg-the-docs.outputs.borged-docs-folder }}
#           build-command: make epub
#       - uses: usnistgov/sphinx-action@latexpdf
#         name: Build PDF
#         with:
#           docs-folder: ${{ steps.borg-the-docs.outputs.borged-docs-folder }}
    - name: Commit documentation changes
      uses: usnistgov/NISTtheDocs2Death@update_pages
      with:
        docs-folder: ${{ steps.borg-the-docs.outputs.borged-docs-folder }}
        separated-layout: ${{ inputs.separated-layout }}
        default-branch: ${{ github.event.repository.default_branch }}
        pages-branch: ${{ inputs.pages-branch }}
        pages-url: ${{ inputs.pages-url }}
    - name: Change ownership
      shell: bash
      run: |
        sudo chown -R runner:docker __nist-pages
    - name: DEBUG
      shell: bash
      run: |
        echo "::warning::github.event_name=${{ github.event_name }}"
        echo "::warning::github.event.pull_request.head.repo.full_name=${{ github.event.pull_request.head.repo.full_name }}"
        echo "::warning::github.repository=${{ github.repository }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ inputs.pages-branch }}
        directory: __nist-pages
        github_token: ${{ github.token }}
      # Pull requests from forked repos don't have permissions
      # to push back to pages-branch
      if: >-
        (
          github.event_name != 'pull_request'
          || github.event.pull_request.head.repo.full_name == github.repository
        )
    - uses: actions/upload-artifact@v3
      name: Upload Documentation Artifacts
      with:
        name: ${{ github.event.repository.name }}-${{ env.SANITIZED_REF_NAME }}-${{ github.sha }}
        path: |
          ${{ steps.borg-the-docs.outputs.borged-docs-folder }}/${{ env.BUILD_DIR }}/html
#             ${{ steps.borg-the-docs.outputs.borged-docs-folder }}/${{ env.BUILD_DIR }}/epub/*.epub
#             ${{ steps.borg-the-docs.outputs.borged-docs-folder }}/${{ env.BUILD_DIR }}/latex/${{ github.event.repository.name }}.pdf
      # Use always() to always run this step to publish documentation
      # artifacts even when there are failures
      if: ${{ always() }}
