# This is a basic workflow that is manually triggered

name: NISTtheDocs2Death
description: Deploys Sphinx-built documentation to https://pages.nist.gov
author: Jonathan Guyer

inputs:
  docs_folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  pages_branch:
    description: 
      The branch linked to your documentation server.
    default: 'nist-pages'
  pages_url:
    description:
      URL of web server for served documentation.
    default: 'https://pages.nist.gov'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set env
      shell: bash
      # In a PR, github.ref_name can be, e.g., `12/merge`,
      # which causes downstream grief.
      run: |
        refname=${{ github.ref_name }}
        echo "SANITIZED_REF_NAME=${refname////_}" >> $GITHUB_ENV
    - name: Commit documentation changes
      uses: usnistgov/NISTtheDocs2Death@workhorse
      with:
        action: borg_the_docs
        docs_folder: ${{ inputs.docs_folder }}
    - uses: usnistgov/sphinx-action@master
      name: Build HTML
      with:
        docs_folder: ${{ inputs.docs_folder }}
#       - uses: usnistgov/sphinx-action@master
#         name: Build ePUB
#         with:
#           docs_folder: ${{ inputs.docs_folder }}
#           build-command: make epub
#       - uses: usnistgov/sphinx-action@latexpdf
#         name: Build PDF
#         with:
#           docs_folder: ${{ inputs.docs_folder }}
    - name: Commit documentation changes
      uses: usnistgov/NISTtheDocs2Death@workhorse
      with:
        action: update_pages
        docs_folder: ${{ inputs.docs_folder }}
        default-branch: ${{ github.event.repository.default_branch }}
        pages_branch: ${{ inputs.pages_branch }}
        pages_url: ${{ inputs.pages_url }}
    - name: Change ownership
      shell: bash
      run: |
        sudo chown -R runner:docker __nist-pages
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ inputs.pages_branch }}
        directory: __nist-pages
        github_token: ${{ github.token }}
    - uses: actions/upload-artifact@v3
      name: Upload Documentation Artifacts
      with:
        name: ${{ github.event.repository.name }}-${{ env.SANITIZED_REF_NAME }}-${{ github.sha }}
        path: |
          docs/_build/html
#             docs/_build/epub/*.epub
#             docs/_build/latex/${{ github.event.repository.name }}.pdf
      # Use always() to always run this step to publish documentation
      # artifacts even when there are failures
      if: ${{ always() }}
