name: "NISTtheDocs2Death workhorse"
description: "Python Container to do actual work"
author: "Jonathan Guyer"
inputs:
  action:
    description:
      Subcommand to perform [borg_the_docs, update_pages].
    required: true
  docs_folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  default_branch:
    description:
      The default branch configured in GitHub.
    required: false
    default: "main"
  pages_branch:
    description: 
      The branch linked to your documentation server.
    required: false
    default: 'nist-pages'
  pages_url:
    description:
      URL of web server for served documentation.
    required: false
    default: 'https://pages.nist.gov'
runs:
  using: "docker"
  image: "Dockerfile"
